import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img src="" alt="" />
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about-us">About Us</a>
        </nav>
      </header>
      <main className={styles.main}>
        <a href=''>
          <img></img>
          <h2>Events in London</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi voluptates error illo commodi ex, id ipsum velit quas. Nemo,
             error harum voluptas ipsam totam tempore dolorem dignissimos odit, ab ex, molestias itaque modi explicabo cumque sunt minima laboriosam rem! Quisquam dolores aliquam necessitatibus perspiciatis ipsam,
             perferendis voluptate rerum! Suscipit, nisi.</p>
        </a>
        <a href=''>
          <img></img>
          <h2>Events in San Francisco</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi voluptates error illo commodi ex, id ipsum velit quas. Nemo,
             error harum voluptas ipsam totam tempore dolorem dignissimos odit, ab ex, molestias itaque modi explicabo cumque sunt minima laboriosam rem! Quisquam dolores aliquam necessitatibus perspiciatis ipsam,
             perferendis voluptate rerum! Suscipit, nisi.</p>
        </a>
        <a href=''>
          <img></img>
          <h2>Events in Madrid</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi voluptates error illo commodi ex, id ipsum velit quas. Nemo,
             error harum voluptas ipsam totam tempore dolorem dignissimos odit, ab ex, molestias itaque modi explicabo cumque sunt minima laboriosam rem! Quisquam dolores aliquam necessitatibus perspiciatis ipsam,
             perferendis voluptate rerum! Suscipit, nisi.</p>
        </a>
      </main>
    </>
  )
}
