import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link';
import Dummy from '@/components/dummy';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className={styles.container}>
      <Dummy></Dummy>
      <style jsx>
        {`
        .mySpan{
          color: red;
        }
        `}
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name='keywords' content='nextJs,huntingCoder blog, hunting coder'></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.mainNav}>
        <ul>
          <Link href='/'><li>Home</li></Link>
          <Link href='/about'><li>About</li></Link>
          <Link href='/blog'><li>Blog</li></Link>
          <Link href='/contact'><li>Contact</li></Link>
        </ul>
      </nav>
      <main className={styles.main}>
        

        <div className={styles.center}>
          <span className="mySpan dummy">
          <h1>Hunting Coder</h1>
          </span>
        </div>

        <div className={styles.center}>
          <p>
            A blog for the coders by a coder.
          </p>
        </div>

        <div className="blogs">
          <h2>Popular Blogs</h2>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022</h3>
            <p>JavaScript is a language used for designing web pages
            </p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022</h3>
            <p>JavaScript is a language used for designing web pages
            </p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022</h3>
            <p>JavaScript is a language used for designing web pages
            </p>
          </div>
        </div>
        
      </main>
      </div>
  )
}
